services:
  cloudserver:
    image: ghcr.io/scality/cloudserver:9.2.8
    platform: linux/amd64
    ports:
      - "8000:8000"
    environment:
      S3BACKEND: mem
      REMOTE_MANAGEMENT_DISABLE: "1"
      LOG_LEVEL: info
      ENDPOINT: "cloudserver,s3.docker.internal,localhost,127.0.0.1"

  mc:
    image: minio/mc:latest
    depends_on:
      - cloudserver
    entrypoint: >
      /bin/sh -c "
      until (mc alias set cloudserver http://cloudserver:8000 accessKey1 verySecretKey1) do echo '...waiting...' && sleep 1; done;
      mc mb -p cloudserver/warehouse;
      tail -f /dev/null
      "

  iceberg-rest:
    image: tabulario/iceberg-rest:latest
    depends_on:
      - mc
    ports:
      - "8181:8181"
    environment:
      AWS_REGION: us-east-1
      AWS_ACCESS_KEY_ID: accessKey1
      AWS_SECRET_ACCESS_KEY: verySecretKey1
      CATALOG_WAREHOUSE: s3://warehouse/
      CATALOG_IO__IMPL: org.apache.iceberg.aws.s3.S3FileIO
      CATALOG_S3_ENDPOINT: http://cloudserver:8000
      CATALOG_S3_ACCESS__KEY__ID: accessKey1
      CATALOG_S3_SECRET__ACCESS__KEY: verySecretKey1
      CATALOG_S3_PATH__STYLE__ACCESS: "true"
      CATALOG_S3_REGION: us-east-1

  duckdb:
    image: duckdb/duckdb:latest
    depends_on:
      - iceberg-rest
    stdin_open: true
    tty: true
